services:
  - type: web
    name: omniservice
    env: static
    staticPublishPath: .
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
